spring.application.name=patient-service

server.port=8081

# Database Configuration (MongoDB)
spring.data.mongodb.uri=mongodb://localhost:27017/healthcare_db

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/HealthcareRealm

# Redis Cache Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=${spring.application.name}

# Jaeger Tracing
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://jaeger:4318/v1/traces